server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/his?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai"
    username: root
    password: '031126'
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging: { level: { com.example.drug.mapper: debug } }
